In [ ]:
import numpy as np #numpyをモジュールとしてimport.慣例としてnumpyのモジュールにnpというs別名をつける


In [ ]:
a = np.array([0, 1, 2]) #NumPyの配列を作るには np.array() メソッドを使う。0, 1, 2という3つの要素をもつリストを np.array() に指定してNumPyの配列を作った。
print(type(a)) #「NumPyの配列」のデータ型は ndarray 
print(a) #print(a) で、すべての配列要素を表示。一瞬リストと見分けがつかない点は注意
print(a.dtype) #dtype は、ndarrayのオブジェクトが何の型のデータを保存できるかという情報を格納するプロパティ。NumPyにおいて整数値のデフォルトは int64

<class 'numpy.ndarray'>
[0 1 2]
int64


In [ ]:
b = np.array([1, 1.5, 2]) #浮動小数は float64
print(b)
print(b.dtype)

c = np.array([True, False, True, False, False]) #真偽値の場合 bool がデフォルトの配列のデータ型
print(c)
print(c.dtype)

d = np.array(list("TechAcademy")) #文字列の場合は <U。U の後ろの数値は、文字列の最大文字数です。上記の例はすべて1文字の要素なので <U1 となる
print(d)
print(d.dtype)

[1.  1.5 2. ]
float64
[ True False  True False False]
bool
['T' 'e' 'c' 'h' 'A' 'c' 'a' 'd' 'e' 'm' 'y']
<U1


In [8]:
e = np.array([100, 200, 300], dtype = np.int16) #array() で配列を作る際に dtype = np.データ型 という引数を指定することで、もう少し小さいサイズの整数値・浮動小数値として扱え
print(e)
print(e.dtype)

[100 200 300]
int16


In [7]:
f = np.array([1.5, 2.5, 3.5])
print(f)
print(f.dtype)

[1.5 2.5 3.5]
float64


In [ ]:
f = f.astype(np.int64) #途中でデータ型を変更したい場合は astype() を使う。float64 型の配列 f を int64 の整数型に変換
print(f)
print(f.dtype)

[1 2 3]
int64


In [10]:
#連続する整数値で ndarray を作りたい場合は np.arange() メソッドを使う
a = np.arange(20) #（np.arange(n)）なら 0以上n未満
print(a)

b = np.arange(1, 21) #引数が2つ（np.arange(a, b)）なら a以上b未満
print(b)

c = np.arange(2, 41, 2) #引数が3つ（np.arange(x, y, z)）なら x以上y未満（増分：z）
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [11]:
#np.linspace(),np.linspace(a, b, c) と指定することで、a以上b以下の数値をc分割 して作った配列を作れる
d = np.linspace(0, 10, 5) #0以上10以下までの数値を5分割.NumPyでは整数値と小数値が混在した場合は、すべての要素が小数値となります。0.,5.,10.と表示される
print(d)

[ 0.   2.5  5.   7.5 10. ]


In [12]:
e = np.empty(5) #とりあえず指定の要素数をもつ配列だけを用意しておいて、あとから各要素に代入したい」というときは np.empty().ただし、np.empty() は各要素を初期化しないので、要素の初期値は保証できない
print(e)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
#配列を先に作っておきたいものの、確実に何らかの値で初期化しておきたいときは np.zeros()を使う.oで初期化を行う
f = np.zeros(5)
print(f)

[0. 0. 0. 0. 0.]


In [14]:
#すべて1で初期化する np.ones() メソッドも存在
f1 = np.ones(5)
print(f1)

[1. 1. 1. 1. 1.]


In [15]:
#すべての要素の初期値をランダムな数値で作成するなら np.random.rand()
g = np.random.rand(5) #引数は要素数です。0以上1未満のランダムな小数値を初期値とした配列ができあがる
print(g)


[0.54566467 0.34385143 0.9172061  0.38750707 0.714593  ]


In [16]:
#取得したgを1から6までの範囲内の整数値に変換する
g = g * 6 + 1
g = g.astype(np.int8) #整数値に変換したい場合は astype() を使って、整数のデータ型に変換
print(g)

[4 3 6 3 5]


In [17]:
#すでにある2つの配列を連結させたいときは np.concatenate()
h = np.arange(1, 4)    # [1, 2, 3]
i = np.arange(4, 7)    # [4, 5, 6]
j = np.concatenate([h, i])
print(j)

[1 2 3 4 5 6]


In [18]:
#配列としてデータ処理を行なったあとでリストに戻してデータ管理したい場合は tolist()
gl = g.tolist() #rand() のところで作成した配列 g を使った例
print(gl)


[4, 3, 6, 3, 5]


In [19]:
#多次元配列
a = np.array([[1, 2, 3], [4, 5, 6]]) #多次元のリストやタプルを np.array() メソッドの引数に指定
print(a)


[[1 2 3]
 [4 5 6]]


In [20]:
#empty() なども多次元配列の作成に使える。
a = np.empty((2, 3), dtype=np.int64) #1つ目の引数は (縦の要素数, 横の要素数) というタプル形式のデータを指定

a[0] = [1, 2, 3]
a[1] = [4, 5, 6]

print(a)


[[1 2 3]
 [4 5 6]]


In [21]:
#1次元配列を多次元配列に変換するreshape()
a = np.arange(1, 21)
print(a) #配列名.shapeで、該当の配列の構造を知る
print(a.shape) #出力結果の(20,) は、要素数が20個の1次元配列を意味

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)


In [25]:
#1次元配列を多次元配列に変換するreshape().reshape(x, y) は、縦x行・横y列の2次元配列 を作成
b = a.reshape(4, 5)#reshape(4, 5)を使って「要素数20個の配列」から「要素数5個の配列を4個もつ2次元配列」を新たに生成
print(b)
print(b.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)


元の配列と要素数が同一であれば reshape() を使えます。元の配列が要素数20個なのに reshape(3, 6) は実行できません。3 x 6 = 18個となり要素数が合わないため

In [ ]:
b3 = a.reshape(2, 2, 5) #引数を3つ以上に設定すれば3次元以上の配列が作成できる
print(b3)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [ ]:
#多次元配列を1次元配列に変換するflatten()とravel()
c = np.arange(1, 21).reshape(4, 5)
d = c.flatten() #flatten() は元の配列をコピーするため、元の配列は変更されずに残ります
print(c)
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
e = c.ravel() #flatten() と同じ処理をするメソッドとして ravel()
#ravel() は内部の処理構造の都合上、元の配列のコピーで作られない場合があり、一方の配列の内容を変更すると他方の内容も上書きされる可能性がある。その代わり処理が高速

print(c)
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [30]:
#要素の参照と更新
a = np.arange(1, 101).reshape(10, 10)
print(a[0, 0])  #2次元配列で指定する際は 配列名[縦][横]、あるいは 配列名[縦, 横].この例は後者。※スライスを用いて範囲指定する場合は、挙動が異なるため 配列名[縦, 横] を用いるように
print(a)

1
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [31]:
print(a[1, 1])            # 1番目のみ

12


In [32]:
print(a[1:3, 1:3])

[[12 13]
 [22 23]]


In [33]:
print(a[1:5:3, 1:5:3])    # 1番目から4番目まで（増分3で）


[[12 15]
 [42 45]]


In [34]:
print(a[:5, :5])          # 先頭から4番目まで

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]


In [35]:
print(a[7:, 7:])          # 7番目から末尾まで

[[ 78  79  80]
 [ 88  89  90]
 [ 98  99 100]]


In [36]:
print(a[::3, ::3])        # 先頭から末尾まで（増分3で）

[[  1   4   7  10]
 [ 31  34  37  40]
 [ 61  64  67  70]
 [ 91  94  97 100]]


In [37]:
print(a[:, :])            # 全体（先頭から末尾まで）

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [39]:
#要素の新規追加,すでに作成した配列の末尾に要素を追加するには np.append() を利用
a = np.arange(1, 20)                # 1から19までで配列を作成.
a = np.append(a, 20)                # 20を追加.最初が要素を追加したい配列、次が追加したいデータを単独のデータもしくはリスト・タプルの形式で指定
a = np.append(a, (21, 22, 23, 24))  # 21から24までを追加
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [40]:
#特定の場所に追加したいときは np.insert()
b = np.arange(1, 6)           # 1から5までで配列を作成
b = np.insert(b, 1, 6)        # 1番目に6を追加.引数は、最初が要素を追加したい配列、次が追加したい場所、最後が追加要素（単体データかリスト・タプル形式）
b = np.insert(b, 3, (7, 8))   # 3番目に7と8を追加
print(b)

[1 6 2 7 8 3 4 5]


In [41]:
#要素の削除.要素の削除には np.delete()
a = np.arange(5)      # [0 1 2 3 4] の配列を作成
a = np.delete(a, 2)   # 2番目を削除
print(a)



[0 1 3 4]


In [ ]:
#四則演算,配列名に単純な数値をたしたり、ひいたりする四則演算の指定をするだけで、すべての要素について加減乗除が可能
a = np.arange(1, 11)
print(a)
print(a + 1) #全ての要素に加算


[ 1  2  3  4  5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10 11]


In [ ]:
print(a - 1) #全ての要素に減算

[0 1 2 3 4 5 6 7 8 9]


In [45]:
print(a * 2)  #全ての要素に乗算
print(a / 2)  #全ての要素に除算

[ 2  4  6  8 10 12 14 16 18 20]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [ ]:
print(a % 2) #全ての要素の割り算の余りを算出（剰余算）

[1 0 1 0 1 0 1 0 1 0]


In [ ]:
#配列同士の演算も可能
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
print(a)
print(b)
print(b + a)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [14 16 18]]


In [48]:
print(b - a)

[[6 6 6]
 [6 6 6]]


In [ ]:
#かけ算とわり算も可能
c = np.arange(1, 5).reshape(2, 2)
d = np.arange(5, 9).reshape(2, 2)
print(c * d)
print(c)
print(d)

[[ 5 12]
 [21 32]]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [50]:
print(c / d)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
#ユニバーサル関数:一度に全要素へ計算処理を適用し、得られた計算結果で新しい配列を作れるものを総称して ユニバーサル関数 と呼んでいます
a = np.random.rand(5)
a = a * 6 + 1

print(a)

[4.48571553 4.95054686 2.46412996 2.9686074  3.72703544]


In [ ]:
print(np.array(np.floor(a), dtype=np.int64)) #切り捨ては np.floor()

[4 4 2 2 3]


In [53]:
print(np.array(np.ceil(a), dtype=np.int64)) #切り上げなら np.ceil()

[5 5 3 3 4]


In [54]:
print(np.array(np.round(a), dtype=np.int64)) #四捨五入なら np.round()

[4 5 2 3 4]


In [ ]:
#axis（軸）,データを縦（上から下）に見ていく場合の軸が axis=0、横（左から右）に見ていく場合の軸は axis=1
a = np.arange(0, 9).reshape(3, 3)
print(a)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [56]:
#axisの利用例1：np.sum()
# 全要素の合計
print(np.sum(a))

36


In [ ]:
#axis=0 とすると、縦方向（上から下）に合計を求める
# 縦方向の合計
print(np.sum(a, axis=0)) #縦方向の要素（列）ごとの合計を1次元配列にしたものが得られ


[ 9 12 15]


In [59]:
#axis=1 とすると、横方向（左から右）に合計を求める
# 横方向の合計
print(np.sum(a, axis=1))


[ 3 12 21]


In [60]:
#axisの利用例2：np.insert(),要素がすべて0で3行3列の配列 a に、要素がすべて1の1次元配列 b を追加する例

a = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
b = np.array([1, 1, 1])

# 配列aの縦と横の要素数を取得
# （このように書くことで変数hには縦の要素数3、変数vには横の要素数3が格納される）
(h, v) = a.shape

print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [64]:
#axis=0 を指定し、上から○行目に b を追加
# 上から2行目にbを追加
c = np.insert(a, 2, b, axis=0)
print(c)

[[0 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 0]]


In [65]:
# 一番下にbを追加
d = np.insert(a, h, b, axis=0)
print(d)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]]


In [66]:
#axis=1 を指定し、左から○列目に b を追加,axis=1 とした場合、追加される b は、縦に要素が並んだ1次元配列
# 左から2番目にbを追加
e = np.insert(a, 2, b, axis=1)
print(e)


[[0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]]


In [67]:
# 一番右にbを追加
f = np.insert(a, v, b, axis=1)
print(f)

[[0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]]


In [68]:
#axisの利用例3：np.delete(),np.delete() も np.insert() と同様,多次元配列で使う場合、axis のキーワード引数を指定
a = np.arange(1, 26).reshape(5, 5)
print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [69]:
#axis=0 を指定して、上から1番目を削除してみます。なお、a.copy() は、配列 a のコピーを作るメソッド
b = a.copy()

# 上から1番目を削除
b = np.delete(b, 1, axis=0)
print(b)

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [71]:
#axis=1 を指定して、左から1番目を削除
c = a.copy()

# 左から1番目を削除
c = np.delete(c, 1, axis=1)
print(c)

[[ 1  3  4  5]
 [ 6  8  9 10]
 [11 13 14 15]
 [16 18 19 20]
 [21 23 24 25]]


In [ ]:
a = np. array([1, 2, 3, 4, 5, 6, 7, 8, 9]) #1から9まで連動した整数の１次元配列aを作成
print(a)
b = np. arange(1, 10) #aと違う方法で1_9までの整数の１次元配列を作成
print(b)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
b = b.reshape(9,1) #bを９行✖️１列の２次元配列に変換
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [78]:
#1以下のような行列の掛け算をこなうことで、9行9列の2次元配列（九九の表）ができる
c = a*b
print(c)


[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


In [80]:
#9行9列の2次元配列を作成、全ての要素を0で初期化
d = np. zeros((9,9))

#dの要素はfloat64型の配置のため、整数int8型に変換
d = d.astype(np.int8)

#二重ループで九九の表を作成
for i in range(9):
    for j in range(9):
        d[i,j] = (i + 1)*(j + 1)

print(d)        



[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
